### ISSUE TITLE
Midi channel change

### ISSUE THREAD

**Issue by ramondebruyn** [dclelland/Gong#12]
Thank you for this incredible library! I was able to get it working on iOS. 

This may be related to the previous question, but is there a way to manually set the channel that the midi data is sent out on? In the example app, it shows as being sent on channel 0. How do I set it to send on different channel?

Thanks again for a wonderful library!

**Comment by dclelland** [comment]
Hi, in the example app the `MIDINote` is initialised like this:
```swift
let note = MIDINote(pitch: pitch)
```
You should be able to specify a channel like this:
```swift
let note = MIDINote(channel: 0, pitch: pitch)
```
