### ISSUE TITLE
takeRetainedValue of propertyName creates zombie when MIDINetworkSession is connected

### ISSUE THREAD

**Issue by VoidRatio** [dclelland/Gong#5]
I’m  aim to add a wrapper for MIDINetworkSession which I intend to use for iPad app, and came across what may be an issue in MIDINotice.

I recreated the example app for iOS and when an external device connects via a MIDI network session  two notifications are generated ( `.propertyChanged` and `.setupChanged`) this appears to  create a zombie `CFString`. I think this is the result of the first notification ( `.propertyChanged` ) retaining the `noticiation.propertyName`. 

`let property = notification.propertyName.takeRetainedValue()`

changing the above to

` let property = notification.propertyName.takeUnretainedValue() `

fixes the issue, although early days so I haven’t fully tested for side effects. 

**Steps to recreate:** 

1) I replicated the test app for an iOS device
2) Using MIDI Network Setup on a Mac I connect to the iPad
3) The the iPad prints the notification for `.propertyChanged` to the debug console
iPad app crashes with `Thread 1: EXC_BAD_ACCESS (code=1, address=0xa6e472e10)`

Using instruments we see.

```
**Zombie Messaged**

An Objective-C message was sent to a deallocated 'CFString (immutable)' object (zombie) at address: 0x2808304e0. 
```

**Comment by dclelland** [comment]
Hi, thanks for letting me know - this memory management stuff can be a little over my head sometimes.

Reading [this post on StackOverflow](https://stackoverflow.com/questions/29048826/when-to-use-takeunretainedvalue-or-takeretainedvalue-to-retrieve-unmanaged-o) suggests to me what you're doing is correct - happy to merge and republish the pod if you flick me a quick PR.

**Comment by dclelland** [comment]
Actually, put in a PR at my end, and also migrated to Swift 5; please let me know how you get on with this: https://github.com/dclelland/Gong/pull/6

**Comment by VoidRatio** [comment]
Hi Daniel,

Thanks a lot for creating this library. I’m new to Swift and iOS dev, your project really gave me a head start in understanding how to use CoreMIDI.
I’m also fairly novice with GitHub but have now created a fork and incorporated Gong into my project as a (local) Swift Package so will continue to test your fix for the memory leak. 

In terms of future contributions would you prefer I raise a pull request or an issue in the first instance? 

All the best, Alex

**Comment by dclelland** [comment]
No problem - I'm just stoked someone's getting some mileage out of it. I built this library also to learn CoreMIDI, and then only played around with it for a few weeks before never really touching it again.

Regarding future contributions; up to you, I'm easy.

**Comment by dclelland** [comment]
Closing as am publishing version 1.2.0 now.
