### ISSUE TITLE
Using in SPM does not work

### ISSUE THREAD

**Issue by Copernicus2012** [dclelland/Gong#8]
When II try to include Gong through XCODE SPM it fails with:

because every version of Gong contains incompatible tools version and root depends on Gong 1.2.0..<2.0.0, version solving failed.

Is there a way to resolve this?
Thanks

**Comment by dclelland** [comment]
There's an open PR which (I think; I don't use SPM (yet)) fixes this but breaks Cocoapods - had a busy few weeks, haven't quite got around to dealing with it yet I'm afraid

https://github.com/dclelland/Gong/pull/7

**Comment by dclelland** [comment]
Merging that PR and republishing now
